# Generated by Django 5.1.3 on 2024-11-14 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('cedula', models.CharField(help_text='ingresa la cedula del docente', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='ingresa el nombre del docente', max_length=50)),
                ('apellido', models.CharField(help_text='ingresa el apellido del docente', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('cedula', models.CharField(help_text='ingresa la cedula del estudiante', max_length=10, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(help_text='ingresa el nombre del estudiante', max_length=50)),
                ('apellido', models.CharField(help_text='ingresa el apellido del estudiante', max_length=50)),
                ('edad', models.PositiveIntegerField(help_text='ingresa la edad del estudiante')),
                ('celular', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Estudiante : ',
                'verbose_name_plural': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto1', models.FloatField()),
                ('producto2', models.FloatField()),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Calificacionutc.docente')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Calificacionutc.estudiante')),
            ],
        ),
    ]
