# Generated by Django 5.1.3 on 2024-11-14 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calificacionutc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='producto3',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='estudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='Calificacionutc.estudiante'),
        ),
    ]
